DIM = 40
INIT_HERB = 400         
INIT_CARN = 80
INIT_ENERGY = 50
MAX_ENERGY = 150

P_INIT_PLANT = 0.3
P_PLANT = 0.1
P_PLANT_NEIGHBOR_FACTOR = 0.1 

P_MUTATION = 0.1

P_REPRODUCE_HERB = 0.6
P_REPRODUCE_CARN = 0.45

ENERGY_IDLE_COST = 2
ENERGY_MOVE_COST = 1    
ENERGY_HUNT_COST = 10
ENERGY_PER_PLANT = 20
ENERGY_PER_PREY = 30
REPRODUCTION_THRESHOLD = 80

MIN_LIFESPAN = 50
MAX_LIFESPAN = 90

MAX_INIT_SPEED = 2      
MAX_INIT_SOCIABILITY = 2
MAX_INIT_VISION = 3
MAX_INIT_ARMOR = 2
MAX_INIT_STRENGTH = 2

W_HERB_FOOD_DIRECT = 10
W_HERB_THREAT = 10

W_CARN_PREY = 10
W_CARN_COMPETITION = 10

FPS = 20